// For those who want the bleeding edge
buildscript {
    repositories {
        //jcenter()
        maven {
            name = "files forge https"
            url = "https://files.minecraftforge.net/maven"
        }
		maven {
            name = "repo"
            url = "https://repo.maven.org/maven2"
        }
		maven {
            name = "repo1"
            url = "https://repo1.maven.org/maven2"
        }
		maven {
		 name = "central"
            url 'https://maven.aliyun.com/repository/central'
        }
		maven {
		 name = "google"
            url 'https://maven.aliyun.com/repository/google'
        }
		maven {
            name = "jcenter"
            url = "https://maven.aliyun.com/repository/jcenter"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
		maven {
		  credentials {
			username '62fc82532b16b2e74110d0f6'
			password 'ZE2Feawlg7O]'
		  }
		  url 'https://packages.aliyun.com/maven/repository/2266638-release-DKyUYN/'
		}
		maven {
		  credentials {
			username '62fc82532b16b2e74110d0f6'
			password 'ZE2Feawlg7O]'
		  }
		  url 'https://packages.aliyun.com/maven/repository/2266638-snapshot-XE0aNZ/'
		}
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'idea'
idea{
    module{
        inheritOutputDirs = true
    }
}

version = "1.8.9-1.0.6 Beta"
group= "com.trhsy.sim" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "simulated"

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "eclipse"
    mappings = "stable_22"
}

dependencies {
  

}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
[compileJava,compileTestJava]*.options*.encoding = 'UTF-8'
compileJava.options.fork = true
compileJava.options.forkOptions.executable = "D:\\java\\jdk1.8.0_271\\bin\\javac.exe"