# Define the root logger with file appender
log4j.rootLogger = DEBUG,FILE,STDOUT
# Define the file appender
log4j.appender.FILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FILE.File=logs/run.log
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
log4j.appender.FILE.DatePattern='_'yyyy-MM-dd

# ??????????
#??????????log4j.appender.appenderName = fully.qualified.name.of.appender.class.
#### ConsoleAppender:????? ####
log4j.appender.STDOUT = org.apache.log4j.ConsoleAppender
# ??????
log4j.appender.STDOUT.Target = System.out
# ???????????
log4j.appender.STDOUT.Threshold = INFO
# ???? true, ????????
log4j.appender.STDOUT.ImmediateFlush = true
# ??????
log4j.appender.STDOUT.Encoding = UTF-8
# ??????
log4j.appender.STDOUT.layout = org.apache.log4j.PatternLayout
# ?????????PatternLayout ??????????ConversionPattern??????
log4j.appender.STDOUT.layout.ConversionPattern =[%d{yyyy-MM-dd HH:mm:ss,SSS}]-[%p] -%c -%r -%l.%M(%L) | %m%n