# ??rootLogger?info?????????all_appender?console_appender
log4j.rootLogger=error,all_appender,console_appender
# ????Logger????debug??????:console_appender?bd_data_appender
log4j.logger.debugLogger=debug,console_appender,bd_data_appender
log4j.logger.infoLogger=info,console_appender,info_appender
log4j.logger.warnLogger=warn,console_appender,warn_appender
log4j.logger.errorLogger=error,console_appender,error_appender
log4j.logger.fatalLogger=fatal,console_appender,fatal_appender

#??????
log4j.appender.console_appender=org.apache.log4j.ConsoleAppender
log4j.appender.console_appender.layout=org.apache.log4j.PatternLayout    #???????
log4j.appender.console_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
#?info?????????????????
log4j.appender.info_appender=org.apache.log4j.RollingFileAppender
log4j.appender.info_appender.File=mm_logs/info.log    #?????
log4j.appender.info_appender.MaxFileSize=20000KB    #????20000KB??????info.log.1?info.log.2?info.log.3...??info.log.30
log4j.appender.info_appender.MaxBackupIndex=30    #????30???
log4j.appender.info_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.info_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
#?warn?????????????????
log4j.appender.warn_appender=org.apache.log4j.RollingFileAppender
log4j.appender.warn_appender.File=mm_logs/warn.log
log4j.appender.warn_appender.MaxFileSize=20000KB
log4j.appender.warn_appender.MaxBackupIndex=30
log4j.appender.warn_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.warn_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
#?erro?????????????????
log4j.appender.error_appender=org.apache.log4j.RollingFileAppender
log4j.appender.error_appender.File=mm_logs/error.log
log4j.appender.error_appender.MaxFileSize=20000KB
log4j.appender.error_appender.MaxBackupIndex=30
log4j.appender.error_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.error_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
#?fatal?????????????????
log4j.appender.fatal_appender=org.apache.log4j.RollingFileAppender
log4j.appender.fatal_appender.File=mm_logs/fatal.log
log4j.appender.fatal_appender.MaxFileSize=20000KB
log4j.appender.fatal_appender.MaxBackupIndex=30
log4j.appender.fatal_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.fatal_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
#?info?????????????????Logger????rootLogger??
log4j.appender.all_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.all_appender.File=mm_logs/all.log    #????
log4j.appender.all_appender.layout=org.apache.log4j.PatternLayout    
log4j.appender.all_appender.layout.ConversionPattern=%-d{yyyy-MM-dd HH\:mm\:ss}-%t-[%p]\: %m%n
log4j.appender.all_appender.DatePattern='.'yyyy-MM-dd    #?????? ?????????????????????all.log.2017.10.29
#?debug????????????????
log4j.appender.bd_data_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.bd_data_appender.File=mm_logs/data.log
log4j.appender.bd_data_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.bd_data_appender.layout.ConversionPattern=%m%n
log4j.appender.bd_data_appender.DatePattern='.'yyyy-MM-dd

# ===================================================================================
#????????
log4j.logger.com.opensymphony.xwork2=error
log4j.logger.org.apache.commons.httpclient=off
log4j.logger.org.apache.struts2=info

log4j.logger.org.springframework=info
log4j.logger.org.springframework.security=info
log4j.logger.org.springframework.web.filter.CommonsRequestLoggingFilter=warn
log4j.logger.org.quartz=warn

log4j.logger.org.hibernate.type=off
log4j.logger.org.hibernate.ps.PreparedStatementCache=info
log4j.appender.logfile.encoding=UTF-8